# This is a basic workflow to help you get started with Actions

name: Release Hubidentity SDK CI

# Controls when the action will run. Triggers the workflow on push
# events but only for tags v*.*.*
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ANDROID_GH_PAT }}

      - name: Set env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Release
        run: ./gradlew assembleRelease
        env:
          GPR_USER: ${{ secrets.GPR_USER_ID }}
          GPR_PAT: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}
          VERSION_NAME: ${{ env.RELEASE_VERSION }}

      - name: Publish packages
        run: ./gradlew publish
        env:
          GPR_USER: ${{ secrets.GPR_USER_ID }}
          GPR_PAT: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}
          VERSION_NAME: ${{ env.RELEASE_VERSION }}